project_id: '464702'
api_token_env: 'CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files: [
    # JSON translation files
    {
      source: '/i18n/en/**/*',
      translation: '/i18n/%locale%/**/%original_file_name%',
    },
    # Docs Markdown files
    {
      source: '/docs/**/*',
      translation: '/i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%',
    },
  ]
